ALTER SESSION SET ISOLATION_LEVEL = READ COMMITED;
SET TRANSACTION READ WRITE;
SELECT 'Tr A: ' || GET_IDS_AND_ISOLATION_LEVEL FROM DUAL; 
SELECT 'Tr A START: ' || GET_CT FROM DUAL;

EXEC DBMS_LOCK.SLEEP(5);

SELECT 'Tr A INSERT: ' || GET_CT FROM DUAL;
INSERT INTO "subscriptions" 
("sb_id", "sb_subscriber", "sb_book", "sb_start", "sb_finish", "sb_is_active") 
VALUES (1000, 1, 1, TO_DATE('2025-01-12', 'YYYY-MM-DD'), 
TO_DATE('2026-01-12', 'YYYY-MM-DD'), 'N');

EXEC DBMS_LOCK.SLEEP(10);

SELECT 'Tr A ROLLBACK: ' || GET_CT FROM DUAL;
ROLLBACK;

--ANOTHER SESSION 


ALTER SESSION SET ISOLATION_LEVEL = READ COMMITED;
SET TRANSACTION READ WRITE; 
SELECT 'Tr B: ' || GET_IDS_AND_ISOLATION_LEVEL 
FROM DUAL; 
SELECT 'Tr B START: ' || GET_CT 
FROM DUAL;

SELECT 'Tr B COUNT-1: ' || GET_CT FROM DUAL;
SELECT COUNT(*) 
FROM "subscriptions" 
WHERE "sb_id" > 500;

EXEC DBMS_LOCK.SLEEP(10);

SELECT 'Tr B COUNT-2: ' || GET_CT 
FROM DUAL; 
SELECT COUNT(*) 
FROM "subscriptions" 
WHERE "sb_id" > 500;

EXEC DBMS_LOCK.SLEEP(15);

SELECT 'Tr B COUNT-3: ' || GET_CT 
FROM DUAL;
SELECT COUNT(*) 
FROM "subscriptions" 
WHERE "sb_id" > 500;
SELECT 'Tr B COMMIT: ' || GET_CT 
FROM DUAL;
COMMIT;
