ALTER SESSION SET ISOLATION_LEVEL = SERIALIZABLE;
SET TRANSACTION READ WRITE;

SELECT 'START UPD 1 SESSION A ' || GET_CT
FROM DUAL;
UPDATE "subscribers" SET "s_name" = CONCAT("s_name", 'UPD 1 SES A') WHERE "s_id" = 1;

EXEC DBMS_LOCK.SLEEP(5);

SELECT 'START UPD 2 SESSION A ' || GET_CT
FROM DUAL;
UPDATE "books" SET "b_name" = CONCAT("b_name", 'UPD 2 SES A') WHERE "b_id" = 9;
SELECT 'COMMIT SESSION A' || GET_CT
FROM DUAL;
COMMIT;

----ANOTHER SESSION 

ALTER SESSION SET ISOLATION_LEVEL = SERIALIZABLE;
SET TRANSACTION READ WRITE;

SELECT 'START UPD 1 SESSION B' || GET_CT FROM DUAL;
UPDATE "books" SET "b_name" = CONCAT("b_name", 'UPD 1 SES B') WHERE "b_id" = 9;
SELECT 'UPD 1 DONE SESSION B' || GET_CT
FROM DUAL;

EXEC DBMS_LOCK.SLEEP(5);

SELECT 'START upd 2 SESSION B' || GET_CT FROM DUAL;
UPDATE "subscribers" SET "s_name" = CONCAT("s_name", 'UPD 2 SES B') WHERE "s_id" = 1;

SELECT 'SESSION B COMMIT' || GET_CT
FROM DUAL;
COMMIT;
