/*
ANY COMBINATION OF (SERIALIZABLE, READ COMMITTED) ISOLATION LEVELS WITH 
READ WRITE TRANSACTION TYPE CAN'T ASSURE THAT DEADLOCKS WILL NOT OCCUR. 
READ ONLY TRANSACTION TYPE IN ONE OR BOTH TRANSACTIONS CAN ENSURE THE ABSENCE 
OF DEADLOCKS.
YOU CAN TEST IT USING 622B.sql FILE.
*/