CREATE OR REPLACE PROCEDURE DEL_COMPOSITE_USER_INDEXES
AS
idx_name VARCHAR(30);
drop_ind_query VARCHAR(100);
TYPE ref_curs_type IS REF CURSOR;
rc ref_curs_type;
ind_name_query VARCHAR(1000); 

BEGIN
ind_name_query := 'SELECT INDEX_NAME FROM USER_IND_COLUMNS
WHERE COLUMN_POSITION > 1 AND
INDEX_NAME NOT IN 
(
SELECT CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_TYPE=''P'')';

OPEN rc FOR ind_name_query;
LOOP 
FETCH rc INTO idx_name;
EXIT WHEN rc%NOTFOUND;
drop_ind_query := 'DROP INDEX  " ' || idx_name || ' " ';
EXECUTE IMMEDIATE drop_ind_query ;
DBMS_OUTPUT.PUT_LINE(idx_name || ' dropped');
END LOOP;
END;

EXEC DEL_COMPOSITE_USER_INDEXES; 
--SET SERVEROUTPUT ON;

